apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: lab9-challenge
spec:
  clusterIP: None
  selector:
    app: mongo-wrong-label # BROKEN: Selector does not match StatefulSet pod label (app: mongo-sts)!
  ports:
  - port: 27017
    name: mongo
