# BUG: Requests non-existent StorageClass (ultra-fast-ssd)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
  namespace: break-fix-lab
spec:
  serviceName: "inventory-db-svc"
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          value: "secret123"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ultra-fast-ssd
      resources:
        requests:
          storage: 1Gi
