apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-openshift
  namespace: argocd
spec:
  destination:
    namespace: 'nav220161-dev'
    server: 'https://api.rm1.0a51.p1.openshiftapps.com:6443'
  source:
    path: k8s
    repoURL: https://github.com/technoavengers/python-flask-app.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions: []