apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # BROKEN:
      # 1. Node Anti-Affinity excludes db-node (minikube-m03), leaving only 2 eligible nodes (minikube, minikube-m02).
      # 2. Hard Pod Anti-Affinity (required) prevents 2 frontend pods from sharing a host. With 3 replicas and only 2 nodes, 3rd pod is stuck Pending!
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: NotIn
                values:
                - db-node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
