apiVersion: v1
kind: Pod
metadata:
  name: pod-too-large
spec:
  containers:
  - name: app
    image: nginx:alpine
    resources:
      requests:
        cpu: "2"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
